### ISSUE TITLE
log temperature output to pc over usb / serial

### ISSUE THREAD

**Issue by dreamcat4** [engineertype/Controleo3#10]
A live logging feature / output to pb would be helpful, to check that the profile is progressing as expected. It seems like a good idea, if the MCU is not getting too busy in it's main loop to print that data out every so often.

**Comment by engineertype** [comment]
Good news!  Controleo3 already does that.  It dumps temperature and PID information out over the USB port every second.  The data can be collected then pasted into Excel (or another spreadsheet program) for charting.
