### ISSUE TITLE
UI crashes after playing tuneReflowDone

### ISSUE THREAD

**Issue by DaveAhrendt** [engineertype/Controleo3#12]
Compiled with Adruino IDE 1.89.
Playing the specific tune ReflowDone causes the UI to hang.
On line 102 in tones.ino there is a zero in the list of notes/duration.  Changing this to a non zero value fixes the issue.

**Comment by engineertype** [comment]
Thanks for looking into this.  I've submitted a change:
https://github.com/engineertype/Controleo3/commit/2e2c9f2ce158dec90524d837bc000c392905f93a
