### ISSUE TITLE
Link to latest firmware on https://www.whizoo.com/update needs updating

### ISSUE THREAD

**Issue by jcwren** [engineertype/Controleo3#13]
The link on the https://www.whizoo.com/update page is linking to the older v1.4 version that hangs after the 'play tune' command.

Additionally, the text says "Download the Controleo3 library from GitHub by clicking here.", but it's actually downloading the .zip from whizoo.com.

The `library.properties` file in GitHub still says version 1.1, while the one in the 1.4 zip file on the whizoo.com site says 1.4, so I imagine the GitHub version needs to be updated as well.

```
diff -r Controleo3-master/library.properties Controleo3-1.4/library.properties
1,2c1,2
< name=Controleo3
< version=1.1
---
> name=Controleo3 v1.4
> version=1.4
```

**Comment by engineertype** [comment]
Thanks for bringing this to my attention.  I've updated the ZIP file on whizoo.com.
