### ISSUE TITLE
Unrelated Performance bar at LEARNING_PHASE_THERMAL_INERTIA

### ISSUE THREAD

**Issue by usk-johnny-s** [engineertype/Controleo3#2]
https://github.com/engineertype/Controleo3/blob/47675e6766cbc2b19967f7d8f255674a3a45db14/examples/ReflowWizard/Learn.ino#L359

https://github.com/engineertype/Controleo3/blob/47675e6766cbc2b19967f7d8f255674a3a45db14/examples/ReflowWizard/Learn.ino#L365

These lines should be evaluate 'secondsTo150C' as TYPE_WHOLE_OVEN@L354.

**Comment by engineertype** [comment]
Good catch!  I'll fix this in the 1.5 release.  Thanks for the feedback.  Fortunately this is just a UI issue and doesn't affect oven performance.
Peter

**Comment by engineertype** [comment]
This will be in the 1.5 release before the end of the year
