### ISSUE TITLE
Unclear licensing

### ISSUE THREAD

**Issue by ryanbarry** [engineertype/Controleo3#3]
Hey there, I really appreciate all the work you've put into this project! I've started following your guide to build an oven and am porting the code to run on Teensy-LC (much smaller flash & memory).

I noticed that your README says the code is released under "the CC BY-NC-SA 3.0 license" but the LICENSE file indicates the GPL 3.0 – any case you meant to only release under one of those?

**Comment by engineertype** [comment]
It should be GPL 3.0.  I'll update the README.  Thanks for pointing that out.
