### ISSUE TITLE
Idea of reduce a waste time in a learning sequence.

### ISSUE THREAD

**Issue by usk-johnny-s** [engineertype/Controleo3#4]
My understanding of current learning sequence is follows.

1. INITIAL_RAMP with WHOLE_OVEN
2. measuring CONSTANT with WHOLE_OVEN
3. measureing CONSTANT with BOTTOM_ELEMENT
4. measureing CONSTANT with TOP_ELEMENT
5. measuring INERTIA with WHOLE_OVEN
6. measuring Insulation while Cool-down
7. Stabilize with WHOLE_OVEN
8. measuring INERTIA with BOTTOM_ELEMENT
9. Cool-down
10. Stabilize with BOTTOM_ELEMENT
11. measuring INERTIA with TOP_ELEMENT
12. COOLING
13. DONE

My idea is follows.
1. INITIAL_RAMP with WHOLE_OVEN
2. measuring CONSTANT with WHOLE_OVEN
3. measuring INERTIA with WHOLE_OVEN
4. measuring Insulation while Cool-down
5. measureing CONSTANT with BOTTOM_ELEMENT
6. measuring INERTIA with BOTTOM_ELEMENT
7. Cool-down
8. measureing CONSTANT with TOP_ELEMENT
9. measuring INERTIA with TOP_ELEMENT
10. COOLING
11. DONE

It will reduce a waste time. (reduce a time of stabilizing after a measureing inertia.)

**Comment by engineertype** [comment]
You are right, and it could be better.  V1.5 will reduce the learning time to 25 minutes, and the results will be more accurate and reproducible.  It'll be out before the end of 2019.  Thanks for the feedback, it is appreciated.
