### ISSUE TITLE
Changing temp units in reflow prints 'bake' to screen

### ISSUE THREAD

**Issue by MorganSandercock** [engineertype/Controleo3#6]
When clicking the temperature displayed in the top-right corner of the screen during a reflow, it prints the "bake at" string over the top of the reflow phase/status.
Additionally, pretty much any action on any screen always changes units back to C.

**Comment by MorganSandercock** [comment]
OK, I created this issue so I could try to hook a pull request to the issue, but somehow I fail at pull requests. I can't seem to create a pull for the one-line change that fixes the "always changes" issue.

**Comment by engineertype** [comment]
Thanks for the feedback.  This will be fixed in the 1.5 release later this year.
