### ISSUE TITLE
Feature: Profile pause command

### ISSUE THREAD

**Issue by ssnseawolf** [engineertype/Controleo3#9]
Some scenarios require the temperature to be at a certain level before the part is inserted, such as for annealing plastics. It would therefore be useful to have a pause command, where the Controleo profile execution pauses until it receives a screen tap, so that a part may be inserted in the oven and then the profile resumed.

An implementation could look like this:
```
Pause // Controleo pauses indefinitely until screen is tapped
Pause 60s // Controleo pauses for 60 seconds or until screen is tapped, whichever is first
```
or

```
Maintain 250C and pause // Maintain 250C indefinitely until screen is tapped
Maintain 250C and pause up to 60s // Maintain 250C for 60 seconds or until screen is tapped, whichever is first
```
There is no need for a resume command, in my opinion, as a screen tap would indicate the profile is ready to be resumed.

Though Controleo is excellent for reflow, it can readily be used for myriad other uses (such as annealing) with a pause command. Any consideration that could be given to adding this would be quite appreciated and would increase Controleo's flexibility.

**Comment by engineertype** [comment]
I think the "Wait for x seconds" command handles some of what you want, but I think the "screen tap" idea is a good one.  I'll add it to the 1.5 release.  Thanks for the feedback!
